### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Shyrogan** [MizuSoftware/core#2]
# Settings

This issue is more like a thread to decide what we should do for settings, it will try to discuss every problem we might encounter during the development of the client.

## General

**Delegated settings**: This is a cool point mentioned by @lambdagg, it would be nice being able to create settings based on getters/setters. This would allow us to have common settings between features and basically make any setting as configurable as we want.

**Callback**: When a value is set, we should be able to run callbacks.

## Constraints

**Choices:** we should be able to restrict a value by a value set. Those values should be identifiable and describable (maybe they could be containers ?) for settings serialization.
A good solution would be something like this (I guess)
```java
public static final Set<Mode> CHOICES = Set.of(Mode1, Mode2...)

@Setting @Choices("CHOICES")
public Mode mode = Mode1;
```

**Min**, **Max**, **Step**: A number value could have a minimal value, a maximum value, both, none... An annotation that stores a double should be more than enough to achieve this.

**Comment by lambdagg** [comment]
An idea would be to delegate the `@Choices` annotation to the class that we want to use as a setting itself, meaning the list of choices would be defined only once for this class.
However we may want to modulate what choice we want to make in the drop-down list depending on whether X or Y setting is enabled.
Keeping the thread updated if new ideas come to my mind.
